### ISSUE TITLE
New Travis API requires an Accept Header

### ISSUE THREAD

**Issue by zoffixznet** [kentnl/Net-Travis-API#4]
Hey,

In the [API docs](https://docs.travis-ci.com/api), it now says `Always set the Accept header to application/vnd.travis-ci.2+json.  If you do not set the Accept header, you might retrieve our old API formats. These are deprecated and will be removed soon.`

I cloned and grepped the repo for `vnd.travis` and nothing came up, so I'm assuming you're not setting that header and this module might soon stop working.

Cheers,
ZZ

**Comment by kentfredric** [comment]
There's an apparent fix for this in #3 , but I just haven't been able to get around to doing anything on it yet, sorry.
